### ISSUE TITLE
bot commands not working

### ISSUE THREAD

**Issue by lithenbert** [Ou-su-Bot/Ou-su#2]
I tried to do ou!help
Nothing happened
why is that?
![Screenshot_2020-11-29-14-34-09-49_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/75198001/100535958-f9d19800-324f-11eb-9c60-7e73ba829a25.jpg)

**Comment by Cristian-Sknz** [comment]
At this time the bot was offline due to problems with the host. Could you check if the problem still exists? I want to be sure that this is what happened.

**Comment by Cristian-Sknz** [comment]
It was a problem with the prefix, the default prefix of the bot was wrong. I will close here because the problem has been resolved.
